export enum Actions {
  // Palettes
  PALETTE_DELETE = 'PALETTE_DELETE',
  SET_EDIT_PALETTE = 'SET_EDIT_PALETTE',
  PALETTE_CANCEL_EDIT = 'PALETTE_CANCEL_EDIT',
  PALETTE_UPDATE = 'PALETTE_UPDATE',
  PALETTE_EDIT = 'PALETTE_EDIT',
  PALETTE_CLONE = 'PALETTE_CLONE',

  // Dialogs
  CONFIRM_ASK = 'CONFIRM_ASK',
  CONFIRM_ANSWERED = 'CONFIRM_ANSWERED',
  FRAMES_MESSAGE_SHOW = 'FRAMES_MESSAGE_SHOW',
  FRAMES_MESSAGE_HIDE = 'FRAMES_MESSAGE_HIDE',

  // Frames
  ADD_FRAME = 'ADD_FRAME',
  DELETE_FRAME = 'DELETE_FRAME',
  EDIT_FRAME = 'EDIT_FRAME',
  CANCEL_EDIT_FRAME = 'CANCEL_EDIT_FRAME',
  UPDATE_FRAME = 'UPDATE_FRAME',
  NAME_FRAMEGROUP = 'NAME_FRAMEGROUP',

  // Images
  ADD_IMAGES = 'ADD_IMAGES',
  DELETE_IMAGE = 'DELETE_IMAGE',
  DELETE_IMAGES = 'DELETE_IMAGES',
  EDIT_IMAGE_SELECTION = 'EDIT_IMAGE_SELECTION',
  CANCEL_EDIT_IMAGES = 'CANCEL_EDIT_IMAGES',
  UPDATE_IMAGES = 'UPDATE_IMAGES',
  UPDATE_IMAGES_BATCH_CHANGES = 'UPDATE_IMAGES_BATCH_CHANGES',
  IMAGE_FAVOURITE_TAG = 'IMAGE_FAVOURITE_TAG',
  REHASH_IMAGE = 'REHASH_IMAGE',
  SET_PICK_COLORS = 'SET_PICK_COLORS',
  CANCEL_PICK_COLORS = 'CANCEL_PICK_COLORS',

  // Dropbox
  DROPBOX_LOGOUT = 'DROPBOX_LOGOUT',
  SET_DROPBOX_STORAGE = 'SET_DROPBOX_STORAGE',
  LAST_UPDATE_DROPBOX_REMOTE = 'LAST_UPDATE_DROPBOX_REMOTE',
  DROPBOX_SETTINGS_IMPORT = 'DROPBOX_SETTINGS_IMPORT',
  DROPBOX_START_AUTH = 'DROPBOX_START_AUTH',

  // Git
  SET_GIT_STORAGE = 'SET_GIT_STORAGE',
  GIT_SETTINGS_IMPORT = 'GIT_SETTINGS_IMPORT',

  // Storage (Git + Dropbox)
  STORAGE_SYNC_START = 'STORAGE_SYNC_START',
  JSON_EXPORT = 'JSON_EXPORT',
  JSON_IMPORT = 'JSON_IMPORT',

  // Plugins
  PLUGIN_REMOVE = 'PLUGIN_REMOVE',
  PLUGIN_ADD = 'PLUGIN_ADD',
  PLUGIN_UPDATE_PROPERTIES = 'PLUGIN_UPDATE_PROPERTIES',
  PLUGIN_UPDATE_CONFIG = 'PLUGIN_UPDATE_CONFIG',
  PLUGIN_IMAGE = 'PLUGIN_IMAGE',
  PLUGIN_IMAGES = 'PLUGIN_IMAGES',

  // Progress
  EXECUTE_PLUGIN_PROGRESS = 'EXECUTE_PLUGIN_PROGRESS',
  PRINTER_PROGRESS = 'PRINTER_PROGRESS',
  CREATE_GIF_PROGRESS = 'CREATE_GIF_PROGRESS',

  // WiFi-Printer
  SET_PRINTER_PARAMS = 'SET_PRINTER_PARAMS',
  SET_PRINTER_URL = 'SET_PRINTER_URL',
  REMOTE_CALL_FUNCTION = 'REMOTE_CALL_FUNCTION',
  HEARTBEAT_TIMED_OUT = 'HEARTBEAT_TIMED_OUT',
  PRINTER_FUNCTIONS_RECEIVED = 'PRINTER_FUNCTIONS_RECEIVED',
  PRINTER_DATA_RECEIVED = 'PRINTER_DATA_RECEIVED',
  PRINTER_RESET = 'PRINTER_RESET',

  // Features
  SET_VIDEO_PARAMS = 'SET_VIDEO_PARAMS',
  CANCEL_ANIMATE_IMAGES = 'CANCEL_ANIMATE_IMAGES',
  SHARE_IMAGE = 'SHARE_IMAGE',
  START_DOWNLOAD = 'START_DOWNLOAD',
  DOWNLOAD_SELECTION = 'DOWNLOAD_SELECTION',
  BATCH_TASK = 'BATCH_TASK',
  START_CREATE_RGB_IMAGES = 'START_CREATE_RGB_IMAGES',
  SAVE_NEW_RGB_IMAGES = 'SAVE_NEW_RGB_IMAGES',
  CANCEL_CREATE_RGB_IMAGES = 'CANCEL_CREATE_RGB_IMAGES',

  // Generic action types
  GLOBAL_UPDATE = 'GLOBAL_UPDATE',
  TRY_RECOVER_IMAGE_DATA = 'TRY_RECOVER_IMAGE_DATA',
  IMPORT_FILES = 'IMPORT_FILES',
  ADD_TO_QUEUE = 'ADD_TO_QUEUE',

  // New import workflow
  BITMAPQUEUE_ADD = 'BITMAPQUEUE_ADD',
  BITMAPQUEUE_CANCEL = 'BITMAPQUEUE_CANCEL',
  IMPORTQUEUE_ADD = 'IMPORTQUEUE_ADD',
  IMPORTQUEUE_ADD_MULTI = 'IMPORTQUEUE_ADD_MULTI',
  IMPORTQUEUE_CANCEL = 'IMPORTQUEUE_CANCEL',
  IMPORTQUEUE_CANCEL_ONE = 'IMPORTQUEUE_CANCEL_ONE',
  FRAMEQUEUE_ADD = 'FRAMEQUEUE_ADD',
  FRAMEQUEUE_CANCEL_ONE = 'FRAMEQUEUE_CANCEL_ONE',
}
