export enum Actions {
  // Frames
  ADD_FRAME = 'ADD_FRAME',

  // Images
  ADD_IMAGES = 'ADD_IMAGES',
  DELETE_IMAGE = 'DELETE_IMAGE',
  DELETE_IMAGES = 'DELETE_IMAGES',
  UPDATE_IMAGES = 'UPDATE_IMAGES',
  UPDATE_IMAGES_BATCH_CHANGES = 'UPDATE_IMAGES_BATCH_CHANGES',
  IMAGE_FAVOURITE_TAG = 'IMAGE_FAVOURITE_TAG',
  REHASH_IMAGE = 'REHASH_IMAGE',

  // Misc.
  SAVE_NEW_RGB_IMAGES = 'SAVE_NEW_RGB_IMAGES',
  GLOBAL_UPDATE = 'GLOBAL_UPDATE',
  IMPORTQUEUE_CANCEL = 'IMPORTQUEUE_CANCEL',
}
