name: Build 🧱 and Deploy 🛳 gb-printer-web

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/gb-printer-web/**'
      - 'packages/gb-items-source/**'
      - 'packages/gb-printer-schemas/**'
      - .github/workflows/deploy-gb-printer-web.yml
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 💳
        uses: actions/checkout@v4.1.7

      - name: Setup node 💻
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '24.x'

      - name: Setup pnpm 📦
        uses: pnpm/action-setup@v4

      - name: Add release version to environment variables 🌍
        run: |
          node -e "console.log('RELEASE_VERSION=' + require('./packages/gb-printer-web/package.json').version)" >> $GITHUB_ENV

      - name: Check if tag already exists 🏷
        id: checkTag
        uses: mukunku/tag-exists-action@v1.7.0
        with:
          tag: ${{ env.RELEASE_VERSION }}

      - name: Install pnpm dependencies 🔗
        if: steps.checkTag.outputs.exists == 'false'
        run: pnpm install --frozen-lockfile

      - name: Build for pages 📖
        if: steps.checkTag.outputs.exists == 'false'
        env:
          NEXT_PUBLIC_UMAMI_SRC: https://cloud.umami.is/script.js
          NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }}
          NEXT_PUBLIC_DROPBOX_APP_KEY: ${{ secrets.NEXT_PUBLIC_DROPBOX_APP_KEY }}
          NEXT_PUBLIC_DROPBOX_APP_PATH: ${{ secrets.NEXT_PUBLIC_DROPBOX_APP_PATH }}
          NEXT_PUBLIC_BASE_PATH: /gb-printer-web
        run: |
          pnpm build
          touch packages/gb-printer-web/out/.nojekyll

      - name: Deploy to GitHub-Pages 📖
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        if: steps.checkTag.outputs.exists == 'false'
        with:
          branch: gh-pages
          folder: packages/gb-printer-web/out

      - name: Create Release 🎉 🥳
        uses: softprops/action-gh-release@v2.0.5
        if: steps.checkTag.outputs.exists == 'false'
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Version ${{ env.RELEASE_VERSION }}
